### ISSUE TITLE
add support for python/other languages!

### ISSUE THREAD

**Issue by nmz787** [tokuhirom/git-xlsx-textconv#3]
I just converted your script to Python and am working on trying it out now with git. I tried to do a pull request, but it won't work for a gist:
https://gist.github.com/nmz787/c43bc109db915064f188

Thanks for the code and README!

**Comment by tokuhirom** [comment]
You can create your repo. I don't need python port for me :P

**Comment by nmz787** [comment]
Ok, I didn't want to do that because it's the same functionality, has the
same setup, etc, just different language.

On Fri, May 15, 2015 at 6:50 PM, Tokuhiro Matsuno <notifications@github.com>
wrote:

> You can create your repo. I don't need python port for me :P
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tokuhirom/git-xlsx-textconv/issues/3#issuecomment-102562501>
> .
>



-- 
-Nathan
